name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{secrets.HEROKU_API_NAME}} #Must be unique in Heroku
  #         heroku_email: ${{secrets.HEROKU_API_EMAIL}}
  test1:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automation Test
        uses: actions/checkout@v2
        with:
          repository: damarmustikoaji/durian
          token: ${{secrets.JAMBHU}}
      - uses: actions/checkout@v2
      - name: Automation Test2
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
          cache: npm
          run: |
            ls \
            && cp .env.sample .env \
            && npm install
      - name: Automation Test3
        run: npm run test-api