name: Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAKERESTAPI_BASE_URL: ${{ secrets.FAKERESTAPI_BASE_URL }}
  REQRES_BASE_URL: ${{ secrets.REQRES_BASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          run: echo "coba_urlnya=google.com" > .env
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Set up testing
        uses: actions/checkout@v2
        with:
          repository: damarmustikoaji/durian
          token: ${{secrets.JAMBHU}}
      - name: npm cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/lock.json') }}
      - name: Installing
        run: npm install
      - name: Testing
        run: npm run test-api
      - name: Reporting
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: reports
