name: Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
      - name: Create Connection file
        run: |
          touch connection.php
          echo <?php >> connection.php
          echo Class dbObj { var $servername = "localhost"; var $username = "root"; var $password = ""; var $dbname = "indonetsource"; var $conn; >> test.php
          echo function getConnstring() { $con = mysqli_connect($this->servername, $this->username, $this->password, $this->dbname) or die("Connection failed: " . mysqli_connect_error()); if (mysqli_connect_errno()) {printf("Connect failed: %s\n", mysqli_connect_error());exit();} else {$this->conn = $con;} return $this->conn;}} >> connection.php
          echo ?> >> connection.php
          cat connection.php
  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Clone AT
        uses: actions/checkout@v2
        with:
          repository: damarmustikoaji/durian
          token: ${{secrets.JAMBHU}}
      - name: Setup Config
        run: cp .env.sample .env
      - name: Install Dependencies
        run: npm install
      - name: AT Run
        run: npm run test-api
      - name: Import Results
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: ./reports