name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  automationtest:
    runs-on: ubuntu-latest
    steps:
      - name: Automation Test
        uses: actions/checkout@v2
        with:
          token: ${{secrets.JAMBHU}}
          repository: damarmustikoaji/durian
          path: durian
          run: cd /durian && cp /durian/.env.sample /durian/.env && npm install